config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'constructions#index', as: 'authenticated_root'
  end
  root 'homes#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :constructions, except: :show

  resources :lines, only: :none do
    resources :stations, only: :index
    resources :constructions, only: :index
  end

  resources :users, only: :show do
    resources :reminders, only: :create
  end

  resources :reminders, only: :destroy

  get '/sign_out', to: 'sessions#destroy'
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/homes/index.html.erb
<body class="home">
	<div class="container">
		<div class="component">
				<ul class="grid">
					<li>
						<div class="codrops-header">
							<%= link_to "Breakable Toy :casey", constructions_path, class: "head-title" %>
							<a class="codrops-icon codrops-icon-prev"
								href="https://github.com/caseykim/on-my-way-T">
								<span>GitHub</span>
							</a>
							<a class="codrops-icon codrops-icon-drop"
							href="https://www.linkedin.com/in/caseykkim">
								<span>LinkedIn</span>
							</a>
						</div>
					</li>
					<li class="ot-letter-left"><span data-letter="O">O</span></li>
					<li class="ot-letter-top"><span data-letter="N">N</span></li>
					<li class="ot-letter-right"><span data-letter="-">-</span></li>
					<li class="ot-letter-left"><span data-letter="M">M</span></li>
					<li class="ot-letter-bottom"><span data-letter="Y">Y</span></li>
					<li class="ot-letter-left"><span data-letter="W">W</span></li>
					<li class="ot-letter-right"><span data-letter="A">A</span></li>
					<li class="ot-letter-left"><span data-letter="Y">Y</span></li>
					<li class="ot-letter-top"><span data-letter="!">!</span></li>
					<li class="ot-letter-right"><span data-letter="T">T</span></li>
					<a href="/constructions">
						<li class="ot-letter-left go"><span data-letter=">">></span></li>
					</a>
					<li class="ot-letter-top"><span data-letter="O">O</s
	          pan></li>
					<li class="ot-letter-left"><span data-letter="C">C</span></li>
					<li class="ot-letter-top"><span data-letter="T">T</span></li>
					<li class="ot-letter-right"><span data-letter="1">1</span></li>
					<li class="ot-letter-bottom"><span data-letter="5">5</span></li>
					<li class="ot-letter-right"><span data-letter="'">'</span></li>
				</ul>
			</div>
		</div>
	</div>
</body>