config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'constructions#index', as: 'authenticated_root'
  end
  root 'homes#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :constructions, except: :show

  resources :lines, only: :none do
    resources :stations, only: :index
    resources :constructions, only: :index
  end

  resources :users, only: :show do
    resources :reminders, only: :create
  end

  resources :reminders, only: :destroy

  get '/sign_out', to: 'sessions#destroy'
end

app/models/construction.rb
class Construction < ActiveRecord::Base
  belongs_to :user
  belongs_to :line
  belongs_to :start_station, class_name: 'Station'
  belongs_to :end_station, class_name: 'Station'
  has_many :station_constructions
  has_many :stations, through: :station_constructions


  validates :line, presence: true
  validates :start_station, presence: true
  validates :end_station, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date
  validates :start_time, presence: true
  validate :end_time_after_start_time

  scope :search, -> (station_name) {
    joins(:station_constructions).joins(
      :stations
    ).merge(Station.by_name(station_name)).uniq
  }

  after_create :create_station_constructions

  private

  def affected_stations
    stations = line.lines_stations
    start_i = stations.find_by(station: start_station).station_sequence
    end_i = stations.find_by(station: end_station).station_sequence
    range = start_i <= end_i ? start_i..end_i : end_i..start_i
    stations.where(
      station_sequence: range
    ).joins(:station).all.map(&:station)
  end

  def create_station_constructions
    affected_stations.each do |station|
      StationConstruction.create(station: station, construction: self)
    end
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "can't be before the start date")
    end
  end

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "can't be before the start time")
    end
  end
end

app/controllers/constructions_controller.rb
class ConstructionsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if params[:line_id]
      line = Line.find(params[:line_id])
      @constructions = line.constructions
    elsif params[:station] && params[:station] != ""
      @constructions = Construction.search(params[:station])
    else
      @constructions = Construction.all
    end
    @construction = Construction.new

    respond_to(:html, :js)
  end

  def new
    @construction = Construction.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @construction = current_user.constructions.new(construction_params)
    respond_to do |format|
      if @construction.save
        format.html do
          flash[:notice] = 'New construction added successfully.'
          redirect_to constructions_path
        end
        format.js do
          @constructions = Construction.all
          render :index
        end
      else
        format.html do
          flash[:alert] = @construction.errors.full_messages.join(', ')
          render :new
        end
        format.js do
          @errors = @construction.errors.full_messages.join(', ')
        end
      end
    end
  end

  def edit
    construction = Construction.find(params[:id])
    if signed_in? && current_user == construction.user
      @construction = construction
    elsif !signed_in?
      authenticate_user!
    else
      flash[:alert] = 'You have no permission to edit this posting'
      redirect_to constructions_path
    end
  end

  def update
    @construction = Construction.find(params[:id])
    if @construction.update_attributes(construction_params)
      flash[:notice] = 'Construction updated successfully.'
      redirect_to constructions_path
    else
      flash[:alert] = @construction.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    construction = Construction.find(params[:id])
    if signed_in? && current_user == construction.user
      construction.destroy
      flash[:notice] = 'Construction deleted successfully.'
      redirect_to constructions_path
    elsif !signed_in?
      authenticate_user!
    else
      flash[:alert] = 'You have no permission to edit this posting'
      redirect_to constructions_path
    end
  end

  private

  def construction_params
    params.require(:construction).permit(:line_id,
      :start_station_id, :end_station_id, :start_date, :end_date,
      :start_time, :end_time, :description)
  end
end

app/views/constructions/_constructions_list.html.erb
<% @constructions.each do |construction| %>
  <div class="construction">
    <fieldset id="<%= construction.id %>">
      <legend style="color:<%= construction.line.color %>">
        <%= fa_icon "subway" %>
        <%= construction.line.name %>
        <% if signed_in? && current_user == construction.user %>
        <a href="#" class="show-options"><%= fa_icon "cog" %></a>
        <div class="options right">
          <%= link_to "edit", edit_construction_path(construction) %>
          <%= link_to "delete", construction,
            method: :delete,
            style: "color:grey",
            data: {confirm: "Are you sure?"} %>
        </div>
        <% end %>
      </legend>
      <table>
        <tr>
          <th>From</th>
          <th>To</th>
          <th>Starting on</th>
          <th>Ending on</th>
          <th>Starts at (approx)</th>
          <th>Ends at (approx)</th>
          <th>Description</th>
        </tr>
        <tr>
          <td><%= construction.start_station.name %></td>
          <td><%= construction.end_station.name %></td>
          <td><%= construction.start_date %></td>
          <td><%= construction.end_date %></td>
          <td><%= construction.start_time %></td>
          <td>
            <% if construction.end_time != "" %>
              <%= construction.end_time %>
            <% else %>
              Closing
            <% end %>
          </td>
          <td>
            <% if construction.description != "" %>
              <%= construction.description %>
            <% else %>
              No description provided
            <% end %>
          </td>
        </tr>
      </table>
    </fieldset>
  </div>
<% end %>

app/views/constructions/_error.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/constructions/_form.html.erb
<div class="form construction-form">
  <div class="row header">
    <h1>Construction &nbsp;</h1>
    <p>Thank you for contributing!</p>
  </div>
  <div class="errors"></div>
  <div class="row body">
    <%= form_for @construction, remote: true do |f| %>
      <div class="large-4 columns">
        <%= f.label :line %>
        <%= f.collection_select :line_id, Line.all, :id, :name, prompt: "Select Line" %>
      </div>

      <div class="large-4 medium-6 columns">
        <%= f.label :start_station %>
        <%= f.collection_select :start_station_id, Line.first.stations, :id, :name, prompt: "Select Line first" %>
      </div>

      <div class="large-4 medium-6 columns">
        <%= f.label :end_station %>
        <%= f.collection_select :end_station_id, Line.first.stations, :id, :name, prompt: "Select Line first" %>
      </div>

      <div class="medium-6 columns">
        <%= f.label :start_date %>
        <%= f.date_field :start_date %>
      </div>

      <div class="medium-6 columns">
        <%= f.label :end_date %>
        <%= f.date_field :end_date, min: Date.today %>
      </div>

      <div class="medium-6 columns">
        <%= f.label :start_time %>
        <%= f.time_field :start_time %>
      </div>

      <div class="medium-6 columns">
        <%= f.label :end_time %>
        <%= f.time_field :end_time %>
      </div>

      <div class="medium-7 columns">
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>

      <div class="medium-5 columns">
        <%= f.submit class: "button info" %>
      </div>

      <%= link_to "Back", "#", class: "right", id: "close-modal" %>
    <% end %>
  </div>
</div>

app/views/constructions/_save.js.erb
$("div.errors").html("");
$("div.home-errors").html("");
$(".reveal-modal").html("<%= j render(partial: 'form') %>");
<% if @construction.errors.any? %>
  $("div.errors").html(errorAlert())
<% end %>

function errorAlert() {
  var string = "";
  string += "<div data-alert class='alert-box alert'>";
  string += "<%= @errors %>";
  string += "<a href='#' class='close'>&times;</a>";
  string += "</div>";
  return string;
}

app/views/constructions/create.js.erb
<%= render 'save' %>

app/views/constructions/edit.html.erb
<div class="margin-top">
  <%= render 'form' %>
</div>

app/views/constructions/index.html.erb
<section class="main">
  <div class="row">
    <div class="small-9 columns">
      <%= form_tag constructions_path, method: 'get' do %>
        <div class="row collapse postfix-round search-form">
          <div class="small-8 columns">
            <%= text_field_tag :station, params[:station], placeholder: 'Station name' %>
          </div>
          <div class="small-4 columns">
            <%= submit_tag "Search by Station", name: nil, class: "button postfix" %>
          </div>
        </div>
      <% end %>
      <div id="constructions">
        <% @constructions.each do |construction| %>
          <div class="construction">
            <fieldset id="<%= construction.id %>">
              <legend style="color:<%= construction.line.color %>">
                <%= fa_icon "subway" %>
                <%= construction.line.name %>
                <% if signed_in? && current_user == construction.user %>
                <a href="#" class="show-options"><%= fa_icon "cog" %></a>
                <div class="options right">
                  <%= link_to "edit", edit_construction_path(construction) %>
                  <%= link_to "delete", construction,
                    method: :delete,
                    style: "color:grey",
                    data: {confirm: "Are you sure?"} %>
                </div>
                <% end %>
              </legend>
              <table>
                <tr>
                  <th>From</th>
                  <th>To</th>
                  <th>Starting on</th>
                  <th>Ending on</th>
                  <th>Starts at (approx)</th>
                  <th>Ends at (approx)</th>
                  <th>Description</th>
                </tr>
                <tr>
                  <td><%= construction.start_station.name %></td>
                  <td><%= construction.end_station.name %></td>
                  <td><%= construction.start_date %></td>
                  <td><%= construction.end_date %></td>
                  <td><%= construction.start_time %></td>
                  <td>
                    <% if construction.end_time != "" %>
                      <%= construction.end_time %>
                    <% else %>
                      Closing
                    <% end %>
                  </td>
                  <td>
                    <% if construction.description != "" %>
                      <%= construction.description %>
                    <% else %>
                      No description provided
                    <% end %>
                  </td>
                </tr>
              </table>
            </fieldset>
          </div>
        <% end %>
      </div>
      <div class="row share">
        <%= facebook_button %>
      </div>
      <div id="newConstruction" class="reveal-modal" data-reveal aria-labelledby="New Construction" aria-hidden="true" role="dialog">
        <%= render "form" %>
        <a class="close-reveal-modal" aria-label="Close">&#215;</a>
      </div>
      <% if current_user %>
        <%= link_to "Post New Construction Alert", "", "data-reveal-id".to_sym => "newConstruction", class: "small button", id:"new-construction" %>
      <% end %>
    </div>
    <div class="small-3 columns">
      <div class="side-column">
        <h5>Construction by Line</h5>
        <ul>
          <li style="font-weight:normal">
            <%= link_to "All Lines", constructions_path, style: "color:black" %>
          </li>
          <% Line.all.each do |line| %>
            <li style="background-color:<%= line.color %>">
              <%= link_to line.name, line_constructions_path(line) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/constructions/index.js.erb
$("div.home-errors").html("");
$('#constructions').html("<%= j render(partial: 'constructions_list') %>");
$("div.errors").html(successAlert());
setTimeout(function(){
  $("#newConstruction").foundation('reveal','close');
}, 1000);


function successAlert() {
  var string = "";
  string += "<div data-alert class='alert-box success'>";
  string += "Successfully created";
  string += "<a href='#' class='close'>&times;</a>"
  string += "</div>"
  return string;
}

app/views/constructions/new.html.erb
<div class="margin-top">
  <%= render 'form' %>
</div>

app/views/constructions/new.js.erb
$("div.errors").html("");
$("div.home-errors").html("");
$(".reveal-modal").html("<%= j render(partial: 'form') %>");